version: '3.9'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superSqlPassw0rD
      MYSQL_DATABASE: blog_perso
      MYSQL_USER: super_user
      MYSQL_PASSWORD: simpleSqlPass
    volumes:
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d
  webserver:
    build: ./.docker/server_http/
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    ports:
      - ${PORT}:80
    restart: always
    depends_on:
      - db